services:
  ibmmq:
    image: icr.io/ibm-messaging/mq:latest
    ports:
      - 1414:1414
      - 9443:9443
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: passw0rd
      MQ_APP_PASSWORD: passw0rd
    security_opt:
      - label=disable
    healthcheck:
      test: ["CMD", "dspmq"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
